on:
  push:
    branches:
      - main
jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full git history
        uses: actions/checkout@v2
        with:
          fetch-depth: '0' # Fetch all history

      - name: Create custom rules file
        run: |
          cat <<EOF > custom_rules.json
          {
            "API Key": "[A-Za-z0-9]{32,45}",
            "Generic Token": "[A-Za-z0-9._-]{35,}",
            "Basic Auth Credential": "Basic [A-Za-z0-9+/=]{6,}",
            "Bearer Token": "Bearer [A-Za-z0-9._-]{7,}",
            "Generic Secret": "[A-Za-z0-9]{40,}"
          }
          EOF

      - name: Run TruffleHog on the entire repo
        uses: docker://trufflesecurity/trufflehog:v3.0.0
        with:
          args: trufflehog file://$(pwd) --format=json --output-path trufflehog_report.json --rules custom_rules.json

      - name: Upload TruffleHog report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-report
          path: trufflehog_report.json
